### PR TITLE
Add El Niño (ENSO) index calc from SST workflow

### PR DESCRIPTION
**Pull request by andersy005**
[Rendered notebook]( https://nbviewer.jupyter.org/github/NCAR/ncar-python-tutorial/blob/a319469433be84cf249cc3723631084c11fc340c/notebooks/sample_workflows/noaa_ersst_variability/noaa_ersst_variability.ipynb)

### CODE REVIEW

**Comment by jukent** [comment]
There is minimal text, which is fine since it isn't the first workflow we're going through.

But there aren't many opportunities to test understanding. Should we add more tasks?

**Comment by andersy005** [comment]
@kmpaul, @jukent 

This is ready for another look

**Comment by jukent** [comment]
Looks good to me!

**Comment by kmpaul** [comment]
Taking a look now.

**Pull request merged**
