### PR TITLE
Add small improvements to OHC Notebooks

### PR DESCRIPTION
**Pull request by bonnland**
Please review changes to Notebook 1.    I will look at the remaining Notebooks today.

### CODE REVIEW

**Comment by andersy005** [comment]
Thank you, @bonnland! 

It appears that your folk is behind the master. You may need to run the following commands in order to sync with the upstream master:

`git remote add upstream https://github.com/NCAR/ncar-python-tutorial.git`
`git pull upstream master`
`git push origin master`

**Comment by bonnland** [comment]
@andersy005 The end of Notebook 2 has this code, which produces a warning message for me (using Python 3.7.2, I think):

ds_monthy_mean = ds.groupby('time.month').mean()
ds_monthy_mean

/glade/u/home/bonnland/miniconda3/envs/analysis/lib/python3.7/site-packages/xarray/core/groupby.py:833: FutureWarning: Default reduction dimension will be changed to the grouped dimension in a future version of xarray. To silence this warning, pass dim=xarray.ALL_DIMS explicitly.
  allow_lazy=True, **kwargs)

Do we want to modify the code to prevent the warning?

**Comment by andersy005** [comment]
I would change it to `ds_monthy_mean = ds.groupby('time.month').mean(xr.ALL_DIMS)`

**Comment by bonnland** [comment]
@andersy005 I found a potential issue with Notebook 4.  

This is the solution for Task 1, Notebook 4:

# %load solutions/solution_4_1.py
def calc_ocean_heat(delta_level, temperature):
    rho = 1026  # kg/m^3
    c_p = 3990  # J/(kg K)
    weighted_temperature = delta_level * temperature
    heat = weighted_temperature.sum(dim="lev") * rho * c_p
    return heat

In it, you use the sum() function, which I think was not covered before.   I wonder if this is going to cause problems or questions to arise.
It would probably be OK to briefly mention the existence of sum() for variables, before introduction the task.

**Comment by andersy005** [comment]
Ccing @jukent since she is the primary author of the OHC notebooks...

**Comment by jukent** [comment]
They already see .mean() and .sum() is much the same. I will add a section that covers both of these. It will read something like:

You can apply basic math functions to an Xarray DataArray. Available functions are sum and mean.  ...

Or do you think the questions will be deeper than that?

**Comment by bonnland** [comment]
@jukent   IMHO just an example of how to sum over different dimensions would be enough.   Maybe also, can you sum() or mean() over coordinates as well as dimensions?   Does the distinction matter?

**Comment by bonnland** [comment]
@jukent   Notebook 4 has this line of code: 

heat_Jan_1854 = heat.sel(time=slice('1854-01-01','1854-02-01')).squeeze('time')

I was going to introduce some explanation of the squeeze() function, since it hasn't been covered, but I also noticed that the later plotting seems to work if the call to squeeze() is removed.   Any thoughts about whether it should be covered in the tutorial, or left as a more advanced topic?

**Comment by jukent** [comment]
If it works without it we should leave it out. For me I was having issues without it, but maybe they're not persisting (?)

**Comment by bonnland** [comment]
@jukent   Ah, I am having trouble with the final plot, which says the data must be 2d.     So I will leave the squeeze() in there, and mention briefly what it is doing.  

Also, do you have any objection to the matplotlib figure size being a little larger than the default?  I could put in a command that would roughly double the width and height of each plot.

**Comment by jukent** [comment]
That is the same error I was having, it thought there was third, unit dimension that was messing up the plots. I will have to add a description of squeeze too. Thanks for catching all that.

**Comment by bonnland** [comment]
@jukent . Please review Notebook 4; obviously my changes are suggestions, and you should feel free to override any changes I may have made. 

I removed a sentence about adding units, so that the colorbar could be labeled, because it looked like that was happening already; I hope that was the right choice.     I also made the matplotlib figures bigger.   I didn't see any easy way to do the same for the histogram, but perhaps there are parameters that can be passed to make the figure a little bigger.

**Comment by jukent** [comment]
I'm waiting to merge for the checks to complete, but I approve all your changes. Thank you for making them!!

**Comment by andersy005** [comment]
This looks good to me! The notebook metadata can be left as is since when someone else opens the notebook, the metadata will eventually change.

**Comment by andersy005** [comment]
This looks good! I am merging it.

**Pull request merged**
