### PR TITLE
Filling in a Script of the Z230 tutorial

### PR DESCRIPTION
**Pull request by jukent**
If we're going to be live coding, I am most comfortable if I create a draft of what to say. Here we can flesh out exactly what needs to be covered in more detail than in the notes.

### CODE REVIEW

**Comment by kmpaul** [comment]
@jukent The tests are failing because of the `configure` script, which we are no longer going to use.  So, I'm going to submit a PR to remove the testing of the `configure` script in just a second.  Then your PR should pass tests.

**Comment by jukent** [comment]
Thanks Kevin. I will pull it. I thought I could finish this today, but I was about 1/3 of the way through yesterday, not half. I might need another day or two for part 1.

**Comment by kmpaul** [comment]
That's fine.  And don't worry about the failing tests.  The tests that are failing have now been removed by PR #113.  They will still run in this PR, though, because they are still defined in this PR's `.circleci/config.yml` file.  We'll go ahead and merge when you are ready, even if those tests still fail.

**Comment by kmpaul** [comment]
@jukent The PullBot keeps closing this PR because you are attempting to merge from your `master` branch.  If you use the PullBot, you should try to do your PRs only from non-`master` branches in your fork.

**Comment by kmpaul** [comment]
To re-open this PR, you will need to do a `git pull` and `git push` in the clone of your fork.  Then, the **Reopen...** button should be available below.

**Comment by jukent** [comment]
Yes I thought that maybe this wouldn't happen, despite the pull bot memo, since I set up a draft PR instead of a PR. I will reopen it when I am ready for review.

**Pull request closed without merging**
