### PR TITLE
Updating GH pages site

### PR DESCRIPTION
**Pull request by kmpaul**

### CODE REVIEW

**Comment by kmpaul** [comment]
Yeah.  It would be nice to just have the README copied over automatically, but I'm not sure how to do that...

**Comment by kmpaul** [comment]
I think I figured out how to do this.  I just create a symbolic link to the README.md file in the docs directory.

**Comment by kmpaul** [comment]
Turns out this has to be a hard link, because only the content of the `docs` directory is actually accessible to the GH pages site.

**Comment by andersy005** [comment]
Interesting... I was about to suggest looking into [this](https://stackoverflow.com/questions/41966638/jekyll-on-github-pages-include-markdown-in-another-markdown-file)

I am not sure it will work though :)

**Comment by kmpaul** [comment]
That might be better than my reorganizing the `index.md` file to just link to different section.  (That is, each section is its own page, now.)

**Comment by kmpaul** [comment]
Well...  which do you prefer:

1. one single page for all of the content (i.e., just `index.md` with `include_relative` statements), or
2. multiple pages with links from a central `index.md` file.

**Comment by andersy005** [comment]
> multiple pages with links from a central index.md file.

👍

**Comment by andersy005** [comment]
It appears that the second option doesn't work

**Comment by kmpaul** [comment]
Oh, well.  No worries.

**Pull request merged**
